### ISSUE TITLE
Slack integration documentation

### ISSUE THREAD

**Issue by rtwld** [TobseF/impf-bot#1]
The app works great with email/phone! I couldn't get the Slack integration to work though. Could the developer give instructions on how to set up the Slack integration? 

For example, where does one get the `slackBotApiToken`? `xoxb-*` seems to be a [Bot user token](https://api.slack.com/authentication/token-types#bot). Does the user have to create a bot to integrate impf-bot with Slack?

A slightly more verbose howto would be much appreciated!

**Comment by TobseF** [comment]
Oh... good to know that there are other impf-bot user out there 😉 - And it may also help others with this pain
To make the Slack setup more transparent I added an additional `SLACK_SETUP.md`:
### 🤖🛠 SlackBot Setup
https://github.com/TobseF/impf-bot/blob/master/doc/slack_setup/SLACK_SETUP.md

**Comment by rtwld** [comment]
Yeah, it's seems impf-bot is the only functioning bot on github. Thanks for the Slack setup!
