### ISSUE TITLE
"Es ist ein unerwarteter Fehler aufgetreten" [Bot Protection?]

### ISSUE THREAD

**Issue by madrhr** [TobseF/impf-bot#11]
Seit heute ist glaube ich die Bot Protection nochmal massiv hochgefahren worden. Aktuell hält mein Bot ca. 20min durch bevor ich nach der Eingabe der Codes die im Titel genannte Nachricht erhalte und die Abfrage im Hintergrund einen 429 erhält (Too many requests). Frische, neue IP-Adressen verlängern dies mittlerweile auch nicht mehr. Würde es Sinn falls die Meldung kommt dem ganze automatisch 30min oder ähnliches zu geben und denen keine Anfragen gestellt werden oder besteht bei euch dieses Problem gar nicht?

**Comment by SAMUD** [comment]
Ich habe das Problem auch gehabt. So nach 45min oder auch schneller als ich mal die Pausenzeit auf 5sec runter geschraubt habe.
Halbe Stunde warten und dann geht's wieder.

**Comment by TobseF** [comment]
Um möglichen Limits entgegen zu wirken, habe ich einige Timing Einstellungen in den Properties konfigurierbar gemacht. Außerdem wird nun auch der "Virtueller Warteraum" erkannt. Und dank dem Fix von @ncface wird nun auch das Fehlerfenster berücksichtigt.

**Comment by anp369** [comment]
Das Problem tritt bei mir immer noch auf. Ich habe den Verdacht, dass zu schnelle Eingaben des Codes, die Protection triggern. Wenn ich in so einem Fall die Seite neu lade und den Code von Hand eingebe, komme ich immer durch. Vielleicht wäre [sowas](https://stackoverflow.com/questions/42891515/how-to-slow-down-the-speed-of-send-keys-action-in-a-selenium-script-using-python) eine Option? Ich programmiere leider kein Java oder Kotlin, aber könnte sehr gerne beim testen helfen

**Comment by Pfuenzle** [comment]
Jap, habe heute mittag den Code erhalten, mit dem Bot kommt immer der Fehler, bei manueller Eingabe gehts bei mir auch immer durch. Ich wäre sehr für einen Timer, der 2-3 Sekunden nach dem laden der seite wartet, bevor er den Code eingibt

**Comment by prok42** [comment]
Warum gibt der Bot den Code denn überhaupt ein?
In der Bestätigungsmail mit dem Code ist doch ein Link, der direkt auf die Terminsuche mit dem Code führt, im Schema
https://(Server-id)-iz.impfterminservice.de/impftermine/suche/(Vermittlungscode)/(PLZ) 

Eigentlich könnte man für die Terminsuche direkt diese links kommagetrennt aus einem properties-File nehmen und nacheinander durchprobieren.

**Comment by Pfuenzle** [comment]
Stimmt, das wäre die beste Möglichkeit.
@TobseF  wäre es sehr aufwendig, das als alternative einzubauen?
Hab das Fenster jetzt nochmal beobachtet, und ca jedes 4. bis 5. mal kommt der Code durch, ansonsten kommt der Fehler

**Comment by TobseF** [comment]
Den Link zu generieren und dann direkt anzusteuern, wäre kein Problem. Aber auch die langsame Eingabe mit der Vorschleife aus den [Beispielen](https://stackoverflow.com/questions/42891515/how-to-slow-down-the-speed-of-send-keys-action-in-a-selenium-script-using-python) lässt sich einfach nachrüsten.

Warum ist die Code-Eingabe so realisiert? Weil ich mich mit dem Link-Schema überhaupt nicht beschäftigt hatte. Ich hatte auch das Glück, dass ich nichts optimieren musste, sondern es quasi auf anhieb nach dem Schema "automatisiere die Händische Eingabe" geklappt hat.

Ich habe meine Freizeit aber gerade unter anderem mit der Vorbereitung zweiter Talks belegt... #Eigenwerbung#
📅Mo.17.05 [Kotlin Native & Kotlin Multiplatform in Action
](https://www.andrena.de/event/objektforum-onlineedition-mai-2021)
Deswegen halte ich mich leider gerade mit den Bot-Features zurück. Ne kleine Web UI mit Vaadin wäre dann übrigens mit auf der TODO Liste.

**Comment by prok42** [comment]
Klasse, viel Spaß und Erfolg beim Talk!

**Comment by TimApplepie** [comment]
> Warum gibt der Bot den Code denn überhaupt ein?
> In der Bestätigungsmail mit dem Code ist doch ein Link, der direkt auf die Terminsuche mit dem Code führt, im Schema
> https://(Server-id)-iz.impfterminservice.de/impftermine/suche/(Vermittlungscode)/(PLZ)

Ich habe in meinem [Fork](https://github.com/TimApplepie/impf-bot/commit/c6b785088e09af190fe3c9219ab3e0b492495de4) den Link direkt generiert. Läuft 🙂 
Wichtig ist hierbei, dass in der Locations Konfiguration neben dem "Placement code" auch der Servercode eingetragen ist.

**Comment by sgraf812** [comment]
Ich habe jetzt seit einer Weile sowohl master probiert als auch @TimApplepie's fork, bekomme aber bei beidem weiterhin Error Code 429. Es funktioniert immer dann, wenn ich eine Weile mit der Maus im Fenster herumspiele, daher vermute ich, dass tatsächlich auf Mausaktivität o.Ä. geschaut wird.
