### ISSUE TITLE
gradle run error

### ISSUE THREAD

**Issue by sirhc1893** [TobseF/impf-bot#12]
Hi,

i got the following exception. Im wondering about the path on this exception:
"C:\impf\      oolsseleniumchromedriver.exe"

![image](https://user-images.githubusercontent.com/83662340/117037189-7ccab300-ad06-11eb-9f93-4731ce05b554.png)

# Selenium Chrome Driver Settings
pathDriver = C:\tools\selenium
nameDriver = webdriver.chrome.driver
exeDriver = chromedriver.exe

**Comment by c0rrre** [comment]
Change 
pathDriver = C:\tools\selenium
To
pathDriver = C:/tools/selenium

I had the same and it worked for me

**Comment by sirhc1893** [comment]
> Change
> pathDriver = C:\tools\selenium
> To
> pathDriver = C:/tools/selenium
> 
> I had the same and it worked for me

Perfect! Thanks a lot :-)
