### ISSUE TITLE
Leistungsmerkmale

### ISSUE THREAD

**Issue by benereich** [TobseF/impf-bot#16]
Wofür stehen denn die Leistungsmerkmale L920, L921, L922, L923 ? Sind die Vermittlungscodes an ein Merkmal gebunden? Im anderen offenen Issue wurde erwähnt L921 zu verwenden, passt das noch?

**Comment by lk3de** [comment]
Siehe https://001-iz.impfterminservice.de/assets/static/its/vaccination-list.json

- L920 = Biontech für 16-17jährige
- L921 = Biontech oder Moderna für 18+
- L922 = AstraZeneca für 60+
- L923 = Johnson & Johnson für 18+

Mithilfe der Leistungsmehrkmale wird beim Anfordern eines Vermittlungscodes gesteuert, welche Impfstoffe in den Code "einkodiert" werden können.

**Comment by benereich** [comment]
Vielen Dank :-)
Du warst so blitzschnell, ich konnte nichtmal das Issue schließen als ich gerade die `vaccination-list.json` selbst gefunden hatte 😆 

```
[
    {
        "qualification": "L920",
        "name": "Comirnaty (BioNTech)",
        "tssname": "BioNTech",
	"interval": 40,
        "age": "16-17"
     
    },
	  {
        "qualification": "L921",
        "name": "mRNA-1273 (Moderna)",
        "tssname": "Moderna, BioNTech",
	"interval": 40,
        "age": "18-59"
    },
	{
        "qualification": "L922",
        "name": "COVID-1912 (AstraZeneca)",
         "tssname": "Moderna, BioNTech, AstraZeneca",
        "interval": 40,
          "age": "60+"
    },
    {
        "qualification": "L923",
        "name": "COVID-19 Vaccine Janssen (Johnson & Johnson)",
        "tssname": "Johnson&Johnson",
        "age": "18+"
    }
]
```
