### ISSUE TITLE
Only Windows User-Agents allowed

### ISSUE THREAD

**Issue by mickare** [TobseF/impf-bot#19]
Hi, it seems that only Windows User-Agents are able to get through the first steps.

Linux systems are blocked!

**Comment by TobseF** [comment]
Is this vaccination booking really a system racist?  
Added an option to manual set the user agent. Check it out, if it can solve your problem:
```properties
# It seems that non windows agents are blocked. You can set it to "default" to use the default one of chrome.
# Could be something like: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
userAgent=default
```

**Comment by Pfuenzle** [comment]
Linux Useragent is working fine for me, both in docker and on my main machine

**Comment by mickare** [comment]
I tried like 100 requests manually in Linux without any success. And just after 10 requests in Windows I got at least the age question. I know of at least of three other people who experienced the same, and Macs seems to be affected as well.

**Comment by Pfuenzle** [comment]
Well I can only say that its working for me and one of my friends, both on Linux, but a option to change the useragent is always a good option
