### ISSUE TITLE
Docker image fails booting with error message

### ISSUE THREAD

**Issue by anp369** [TobseF/impf-bot#24]
When using the latest commit(c2f358d) I'm unable to get the bot working.
It throws an `IllegalStateException`. See the full log:

```
xauth:  file /root/.Xauthority does not exist

New 'X' desktop is 769e2417d62f:1

Starting applications specified in /root/.vnc/xstartup
Log file is /root/.vnc/769e2417d62f:1.log

WebSocket server settings:
  - Listen on :6901
  - Flash security policy server
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources
> Task :classes

> Task :run FAILED
Exception in thread "main" java.lang.ExceptionInInitializerError
	at de.tfr.impf.selenium.DriverFactoryKt.createDriver(DriverFactory.kt:10)
	at de.tfr.impf.ReportJob.<init>(ReportJob.kt:16)
	at de.tfr.impf.StartKt.main(Start.kt:4)
	at de.tfr.impf.StartKt.main(Start.kt)
Caused by: java.lang.IllegalStateException: Failed finding property `userAgent`
	at de.tfr.impf.config.KProperties.getProperty(KProperties.kt:21)
	at de.tfr.impf.config.KProperties$LazyProperty.getValue(KProperties.kt:33)
	at de.tfr.impf.config.Config.getUserAgent(Config.kt)
	at de.tfr.impf.config.Config.<clinit>(Config.kt:85)
	... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
3 actionable tasks: 2 executed, 1 up-to-date

```

The docker command used was: ` docker run --name impf-bot -e VNC_PASSWORD=123 -it -p 6901:6901 --rm -v $PWD/config.properties:/app/src/main/resources/config.properties impfbot` where `impfbot` is the locally built docker image.
Did I make a mistake during building?

**Comment by schniggie** [comment]
Looks like `userAgent` is missing from your `config.properties`. Have a look [here](https://github.com/TobseF/impf-bot/blob/master/src/main/resources/config.properties),

**Comment by Pfuenzle** [comment]
Seems like you need to add 
`userAgent=default`
to your config file, as the bot is crashing because it can't find the userAgent value.

@TobseF maybe you should make it that these optional values like userAgent or the slack/telegram option do not necessarily have to be in the config file.

Currently, when they are not in there, the script is crashing even if they are not needed.  Cause of this, you have to check the repo every update for a possible new option in the config file, even if it doesn't affect you

**Comment by anp369** [comment]
> Looks like `userAgent` is missing from your `config.properties`. Have a look [here](https://github.com/TobseF/impf-bot/blob/master/src/main/resources/config.properties),

Thanks that did the trick. It works now
