### ISSUE TITLE
Falsche Erkennung von Terminen?

### ISSUE THREAD

**Issue by prok42** [TobseF/impf-bot#33]
Hallo zusammen,

heute morgen hatte ich es zweimal, dass der Bot bei hinterlegten Vermittlungscodes inkl. ServerId (Also Format` [XXXX-XXXX-XXXX](00X)`) der Meinung war, er hätte einen buchbaren Termin gefunden; der ferngesteuerte Browser zeigte aber lediglich den "Termine suchen"-Button an (also kein geöffnetes Overlay mit tatsächlichen Terminen drin). Bonus-Info: das Impfzentrum war zu dem Zeitpunkt schon wieder auf Warteraum gestellt - uU geht da im Hintergrund ein XHR-Request in die Büsche (bekommt Warteraum HTML statt JSON) und das JS reagiert nicht/falsch/unerwartet darauf und Selenium "findet" die Termin-Struktur.

Leider schlecht dokumentierbar/nachstellbar. Kann sich jemand von euch einen Reim darauf machen?

**Comment by Bergdoc** [comment]
Bei mir ein ähnliches Bild, kann mir aber auch noch keinen richtigen Reim darauf machen (https://github.com/TobseF/impf-bot/issues/2#issuecomment-839660279)

**Comment by madrhr** [comment]
@prok42 du beschreibt das Problem ziemlich gut, ist mir seit ein paar Tagen auch schon aufgefallen. Viel machen kann man da leider auch nicht außer vielleicht die Erkennung von freien Terminen verbessern.

Wenn man halt dann mal durch ist durch den Warteraum hat man meistens nicht mal 10min bis der Warteraum schon wieder für einen aktiv ist bzw. man wieder auf den Warteraum geleitet wird wenn man aktualisiert und dann bekommt man, wie du schon gesagt hast, keine JSON Response mit dem Inhalt, dass keine freien Terminen verfügbar sondern das HTML von der Warteseite wieder, und damit crasht dann die Site bzw. es kommt diese Fehlermeldung mit "Unexpected Token "<" at position..." weil eben JSON erwartet wird aber HTML zurück kommt.

Aber die ganze Warteraum Idee und Umsetzung ist halt nicht gerade wirklich durchdacht

**Comment by prok42** [comment]
Ist es denn mit Selenium möglich, die XHR Responses abzufangen? (Wäre ja irgendwie etwas widersinnig zum Konzept "man testet UI"), aber das wäre vmtl die sicherste Variante - entweder der XHR Request geht durch, es kommt ein JSON mit Terminen -> Termin gefunden, yay! oder eben: XHR Request hat als Response den Warteraum oder eine leere JSON Struktur -> nay

**Comment by timoknapp** [comment]
Der Fehler ist mir auch schon mehrfach vorgekommen. Mir ist dabei aufgefallen, dass die Benachrichtigungen über freie Termine generell etwas zu früh verschickt werden. Innerhalb des Modals zur Terminauswahl befindet sich ein Loadinspinenr "Termine werden abgefragt...". Wenn diese Abfrage länger als 1-2 Sekunden andauert und entsprechend nicht direkt ein Fehler angezeigt wird, get der Bot davon aus, dass es freie Termine gibt und schickt entsprechend fälschlicherweise die Benachrichtigung raus. In den meisten Fällen folgt dann direkt wieder die Meldung, dass keine Termine verfügbar sind:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/11437666/118251351-c30ed780-b4a7-11eb-85aa-705a6c7d8488.png">

Die Idee von @prok42 mit dem Abfangen der Responses wäre hier sicherlich hilfreich um sicherzustellen, dass auch tatsächliich Termine verfügbar sind.

**Comment by prok42** [comment]
Alternativ könnte man hier ja einen ganz "dummen" Timer einbauen, der 20s wartet und dann auf die sichtbaren Elemente prüft, 20s bei 10 Minuten Reservierungszeit wären nicht schlimm und die Implementierung vmtl einfacher als das Abfangen des jsons

**Comment by Bergdoc** [comment]
Der PR von h0nIg sollte das Problem lösen:

https://github.com/TobseF/impf-bot/pull/38#issue-644620851

**Comment by prok42** [comment]
@h0nIg Mit Deinem MR/PR ist die Erkennung bei mir deutlich besser - über die Nacht kamen keine false positives und heute morgen ein "echter" positiver Fall
