### ISSUE TITLE
Question: Terminsuche

### ISSUE THREAD

**Issue by Contexys** [TobseF/impf-bot#43]
Hey, danke für das Veröffentlichen dieses Bots!

Ich habe leider kein passenderen Ort für meine Frage gefunden deshalb steht sie nun hier.

Wenn ich nach neuen Impfterminen (mit Vermittlungscode) suche dann setzt sich der Timer für die Reservierung nicht zurück.
Daher stelle ich mir die Frage ob überhaupt die Möglichkeit besteht, dass nach einer Aktualisierung (innerhalb der 10 Minuten) neue Termine auftauchen.

Falls dazu nichts bekannt ist reichen mir auch eure Erfahrungsberichte.

Danke für die Antwort!

**Comment by prok42** [comment]
Hi,

der Timer hängt, meine ich, am Vermittlungscode, nicht an der Session.

Wenn du den gleichen link von einem anderen Gerät mit dem gleichen Code öffnest, sollte der Timer identisch stehen, oder?

**Comment by Contexys** [comment]
Hi,

wenn ich den gleichen Link bspw. in Chrome öffne und danach den Tab komplett schließe bevor ich den Link erneut aufrufe resetet sich der Timer.

Meine Frage ist allerdings aber ob der Reset bzw. nicht Reset des Timers Auswirkungen darauf hat ob neue Impftermine abgefragt werden oder ich die leere reservierte Liste zurück bekomme.

**Comment by prok42** [comment]
Ah! Gute Frage, sorry, hatte erst nicht verstanden, worum es dir ging

**Comment by Contexys** [comment]
Kein Problem :). Vielleicht weiß ja jemand anderes etwas dazu?

**Comment by PhilipU** [comment]
Hi,

bei Intervallen kleiner 10min bin ich nach einiger Zeit (über Nacht) in die DOS Erkennung reingelaufen und bekam nur noch "429 - Too Many Requests" auf die Ajax Terminanfragen zurück. Das wird leider vom Bot nicht direkt erkannt und ich habe das nur aus Zufall gesehen. Fortan hatte ich immer die JS Console offen um das ab und an zu prüfen. Mit einem 10min Intervall kam das aber nicht mehr vor.

Zumindest bei der Terminsuche mit bereits vorhandenem Vermittlungscode gehe ich davon aus, dass die 10min Sperre Serverseitig umgesetzt ist.

Bei mir hat es dann übrigens nach einigen Tagen geklappt- deshalb vielen Dank an @TobseF! :)

**Comment by Pfuenzle** [comment]
@PhilipU kannst du mir sagen, welche Intervalle du in der Config eingestellt hast? Hab schon ein bisschen rumprobiert, aber bekomme bei einer Terminsuche mit Vermittlungscode immer den Fehler 429

**Comment by PhilipU** [comment]
waitingTime = 590
waitingTimeForUserAction = 15
waitingTimeinWaitingRoom = 1
searchElementTimeout = 10
waitingTimeForBrowser = 5

**Comment by TobseF** [comment]
Ich weiß nicht wie es sich auf die Suche auswirkt, aber wenn bei jedem Check ein "neuer Browser" genommen werden soll, dann lässt sich dass sehr einfach nachrüsten. Vielleicht wird das Cookie mitverwendet um häufige Abfragen zu erkennen. Dann würde es helfen in der `locations`-Schleife den Driver neu aufzubauen:
```kotlin
driver.close()
driver = createDriver()
```
