### ISSUE TITLE
SlackBot

### ISSUE THREAD

**Issue by BurgerKing2k19** [TobseF/impf-bot#44]
Hi, Kann mir jemand erklären, wie man den Slackbot startet? Ich habe in der config alles angepasst aber wie starte ich die SlackClient.kt datei?

**Comment by dirkbloessl** [comment]
Der wird automatisch mit gestartet. Du musst nur das "Hauptprogramm" starten und Slack konfiguriert und aktiviert haben. Dann postet der Bot automatisch.

**Comment by PhilipU** [comment]
Evtl. zielt die Frage auch darauf ab wie man zum erhalten der Channel-ID die main() einmalig ausführt? Das geht z.B. in intelliJ ganz einfach:
![image](https://user-images.githubusercontent.com/1150697/118395552-50d6f800-b64b-11eb-913f-1dc4b462d69d.png)

**Comment by dirkbloessl** [comment]
Noch einfacher an die Channel-ID kommen: rechts-klick auf den Channel-Namen, Link kopieren
<img width="396" alt="Bildschirmfoto 2021-05-16 um 18 14 27" src="https://user-images.githubusercontent.com/811984/118404292-a1ae1700-b672-11eb-9231-e1f676d174b6.png">

Anschließend hat man einen Link im Format: https://xxxxxx.slack.com/archives/C021TU9XXUV
Das C021TU9XXUV wäre dann die ID.

**Comment by BurgerKing2k19** [comment]
Das habe ich gemacht, danke. Kann man das irgendwie testen, ob es auch funktioniert?

**Comment by dirkbloessl** [comment]
Sobald Du den Bot gestartet hast, schickt er eine Meldung in den konfigurierten Channel, dass er jetzt mit der Suche startet.

**Comment by KingLoui1986** [comment]
Allem voran erstmal vielen Dank allen beteiligten für die herausragende Arbeit!

Ich habe nur noch ein paar Verständnisprobleme.
Ich starte den Impf-Bot immer via Docker Container habe in der config.properties File gemäß Doku den Slack API Token, sowie die beiden Bot Channel eingetragen.
Habe vom Impf-Bot allerdings noch keine Message im Slack Chat gelesen beim Programmstart.
Leider bin ich noch nicht so bewandert was Docker / Slack und Co. angeht möchte mich aber aus gegebenem Anlass damit beschäftigen :-)
Ich habe mir ein Slack Test Konto für diesen Anwendung fall angelegt also alles FreePlan falls das mein Problem erklären würde?

**Comment by Pfuenzle** [comment]
Hab es mit Slack noch nicht getestet, aber die Telegram benachrichtigungen funktionieren bei mir
Baust du den Container selber oder nutzt du meinen aus dem Dockerhub? Falls das zweite, gib mal `docker pull pfuenzle/impf-bot:latest` ein, damit sollte das neueste Image geladen werden

**Comment by KingLoui1986** [comment]
Hi @Pfuenzle,

vielen Dank für die Info wieder was gelernt, ich habe immer nur das GitHub Verzeichnis neu geladen, aber die Docker Umgebung nicht aktualisiert aufgrund von Unerfahrenheit im Umgang damit.
Der Fehler ist mir dann aber auch noch beim überfliegen des Config Files aufgefallen hatte auch da einen Fehler bei "false" / "true" geht "enable" einfach nicht.  :-)
Aber vielen Dank für Deine Hilfe die Updates der Docker Umgebung helfen mir bei anderen Problemen auch deutlich weiter.
