### ISSUE TITLE
Telegram Notification

### ISSUE THREAD

**Issue by vladivlad86** [TobseF/impf-bot#46]
Is there a possibility to test the Telegram notification?

**Comment by atpanos** [comment]
With one of the latest commits there should be a notification at bot startup.

**Comment by marcvs** [comment]
I get a badly started up chromium (url looks like "data;") when setting
`telegramEnabled = false`
I'm using the dockerised version on debian/bullseye

**Comment by Sebastian-G** [comment]
This issue is not relevant anymore, please close it.
The Telegram integration is working with the current master version and also with the latest docker image.
