### ISSUE TITLE
aktuellen Chromedriver aus chocolatey ziehen

### ISSUE THREAD

**Issue by prok42** [TobseF/impf-bot#47]
Hi @TobseF 

kleiner Punkt für die Doku (und leider keine Zeit für einen PR):
In Deiner Doku nutzt Du via chocolatey den "selenium-chrome-driver", dieser ist aber veraltet und funktioniert mit einem aktuellen Chrome nicht mehr (siehe https://community.chocolatey.org/packages/selenium-chrome-driver -> Für Chrome Version 84 )

Stattdessen sollte die Doku direkt https://community.chocolatey.org/packages/chromedriver erwähnen, dann passen auch die Versionen zueinander bzw. dort sollten auch zeitnah aktuellere Versionen zu finden sein, wenn wieder neue erscheinen

**Comment by fabicodes** [comment]
Ansonsten könnte man auch via [Webdriver Manager](https://github.com/bonigarcia/webdrivermanager) sich den entsprechenden Driver laden lassen

**Comment by prok42** [comment]
Was es alles gibt, kannte ich noch gar nicht @fabicodes ;-)
Für die Doku sollte es aber vmtl eher die einfachste sinnvolle Lösung sein, ggf. mit einem Hinweis auf eine more sophisticated Lösung :)

**Comment by TobseF** [comment]
Jap... da hab ich auch wieder was dazugelernt 👍

**Comment by fabicodes** [comment]
Achtung, zumindest in der Java Variante scheint wohl immer nur für x86/x64
Varianten die Chromedriver akquiriert zu werden, ARM wohl nicht. Hab
aktuell aber nichts zum testen da, sollte man ggfs tun
