### ISSUE TITLE
Docker on raspberry pi: chromedriver syntax error

### ISSUE THREAD

**Issue by Bergdoc** [TobseF/impf-bot#50]
Hi,
while trying to run docker on a raspberry pi 4 I encountered some issues with chromedriver. Does anyone of you have a running setup with a rpi4 (or 3)? The error occurs when running the docker container, it was built without any problems. I am not a docker expert, is there any way to narrow down the error?

_/app/chromedriver: 1: /ap/chromedriver: Syntax error: "(" unexpected_

![chromedriver syntax error](https://user-images.githubusercontent.com/74468424/118455357-55f28080-b6f9-11eb-9df4-1266398da0a7.png)

**Comment by Pfuenzle** [comment]
I'm pretty sure that that's because the container is using the x64 Chromedriver version, while Raspberry PI has the ARM architecture. Thanks for your find, I'm gonna make a new Dockerfile for ARM and make a pull request

**Comment by Pfuenzle** [comment]
Could you try to run `docker pull pfuenzle/impf-bot:latest` to get the newest image (Or build it yourself with the newest commit) and test if this error persists? Thanks

**Comment by Bergdoc** [comment]
Unfortunately it is not working for me with this fix @Pfuenzle 

![chromedriver syntax error new](https://user-images.githubusercontent.com/74468424/118494876-e0030f00-b722-11eb-8d5f-9547ca50ded3.png)

I did some quick research and maybe we should change to this version for the raspberry pi:
https://ivanderevianko.com/2020/01/selenium-chromedriver-for-raspberrypi
Can you guide me, what would I need to adjust to get the chromedriver version from _sudo apt-get install chromium-chromedriver_ inside docker?

**Comment by Pfuenzle** [comment]
The newest update contains a ChromeDriver Manager, which should automatically get the working version, bit it still seems to get only the x64 version.

To get it to work, replace
`WebDriverManager.chromedriver().setup();` in src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt
with `System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)`

After that, add
`RUN apt-get install chromium-chromedriver`

in the Dockerfile after the line with `WORKDIR /app`

Now build the container and it should work. You may have to adjust the path in the config to `/usr/lib/chromium-browser/` and the filename to `chromedriver`.
I hope it works that way, otherwise I have to think of something else

**Comment by Bergdoc** [comment]
thank you very much for your effort so far!

If I add RUN apt-get install chromium-chromedriver to the Dockerfile, I get some issue:

```
Step 5/13 : RUN apt-get install chromium-chromedriver
 ---> Running in bb2b4a45c1e0
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package chromium-chromedriver
The command '/bin/sh -c apt-get install chromium-chromedriver' returned a non-zero code: 100
```

I installed then chromium-chromedriver locally on the raspberry and adjusted the path as you mentioned, but somehow the ChromeDriver is not found, even if it's there?

![chromedriver not exists](https://user-images.githubusercontent.com/74468424/118508405-776e5f00-b72f-11eb-82b4-d8bf9ede0433.png)

![chromedriver locally](https://user-images.githubusercontent.com/74468424/118508442-7f2e0380-b72f-11eb-8559-dfec095d5aa9.png)

Do I need to do some extra adjustments, If I want to run some package which is not installed in the docker container itself? I guess I need to get more into docker, I like it, but I have no clue about it.

**Comment by Pfuenzle** [comment]
When installing the Chromedriver on the PI, the docker container does not have access to it, as it is basically a independent system. I have found a ARM binary for Chromedriver 90, I'll post a new dockerfile here in a few hours

**Comment by fabicodes** [comment]
> The newest update contains a ChromeDriver Manager, which should automatically get the working version, bit it still seems to get only the x64 version.
> 
> To get it to work, replace
> `WebDriverManager.chromedriver().setup();` in src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt
> with `System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)`
> 
> After that, add
> `RUN apt-get install chromium-chromedriver`
> 
> in the Dockerfile after the line with `WORKDIR /app`
> 
> Now build the container and it should work. You may have to adjust the path in the config to `/usr/lib/chromium-browser/` and the filename to `chromedriver`.
> I hope it works that way, otherwise I have to think of something else

Sorry, I did not know that :(

**Comment by Pfuenzle** [comment]
@fabicodes Dont worry, I also would have assumed it gets the correct architecture, the WebDriverManager is a nice addition anyways :D

@Bergdoc Could you please try this Dockerfile?
```
FROM debian:buster

# install apt dependencies
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip wget git default-jdk chromium=90.0.4430.93-1~deb10u1 xorg tightvncserver autocutsel lxde-core novnc python-websockify 

WORKDIR /app

# download gradle
RUN wget https://services.gradle.org/distributions/gradle-7.0-bin.zip  -P /tmp/ && \
    unzip -d /opt/gradle /tmp/gradle-7.0-bin.zip && \
    rm -rf /tmp/gradle-7.0-bin.zip

# copy whole folder into container
COPY . .

RUN sed -i -e 's/\ \ \ \ val\ chromeDriver\ =\ ChromeDriver(chromeOptions)/\ \ \ \ System.setProperty("webdriver.chrome.whitelistedIps", "");\n\ \ \ \ chromeOptions.addArguments\("--no-sandbox"\);\n\ \ \ \ chromeOptions.addArguments\("--disable-dev-shm-usage"\);\n\ \ \ \ val\ chromeDriver\ =\ ChromeDriver\(chromeOptions\)/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# run gradle build
RUN cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt && \
    /opt/gradle/gradle-7.0/bin/gradle build && \
    cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# setup vnc
RUN echo "# XScreenSaver Preferences File\nmode:		off\nselected:  -1" > /root/.xscreensaver && \
  cat /root/.xscreensaver && mkdir /root/.vnc/ && \
  echo "#!/bin/sh\n/usr/bin/autocutsel -s CLIPBOARD -fork\nxrdb $HOME/.Xresources\nxsetroot -solid grey\n#x-terminal-emulator -geometry  80x24+10+10 -ls -title \"$VNCDESKTOP Desktop\" &\n#x-window-manager &\n# Fix   to make GNOME work\nexport XKL_XMODMAP_DISABLE=1\n/etc/X11/Xsession  &\nx-terminal-emulator -e \"/opt/gradle/gradle-7.0/bin/gradle run 2>&1 | tee  /app/impflog\"" > /root/.vnc/xstartup && \
  chmod +x /root/.vnc/xstartup && \
  cat /root/.vnc/xstartup && \
  mv /usr/share/novnc/vnc.html /usr/share/novnc/index.html && \
  echo "#!/bin/bash\necho -n \${VNC_PASSWORD:-impf-bot} | vncpasswd -f > /root/.vnc/passwd\nchmod 400 ~/.vnc/passwd\n\nexport USER=root\nvncserver :1 -geometry 1920x1080 -depth 24 && websockify -D --web=/usr/share/novnc/ 6901 localhost:5901\ntail -f /app/impflog" > /root/vnc-startup.sh && \
  chmod +x /root/vnc-startup.sh && \
  cat /root/vnc-startup.sh && \
  chmod go-rwx /root/.vnc 

RUN wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

RUN dpkg -i chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

EXPOSE 5901
EXPOSE 6901

CMD ["/root/vnc-startup.sh"]
```

and set the chromedriver path to /usr/bin/

This should download the chromedriver for ARM and it finally should work

**Comment by Bergdoc** [comment]
It works now as it should, thank you @Pfuenzle !
Since you have to revert the changes for the ChromeDriver Manager, I think I'll just add the necessary changes to get it running to the Docker docu section, or what do you think?

**Comment by Pfuenzle** [comment]
```
FROM debian:buster

# install apt dependencies
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip wget git default-jdk chromium=90.0.4430.93-1~deb10u1 xorg tightvncserver autocutsel lxde-core novnc python-websockify 

WORKDIR /app

# download gradle
RUN wget https://services.gradle.org/distributions/gradle-7.0-bin.zip  -P /tmp/ && \
    unzip -d /opt/gradle /tmp/gradle-7.0-bin.zip && \
    rm -rf /tmp/gradle-7.0-bin.zip

# copy whole folder into container
COPY . .

RUN sed -i -e 's/\ \ \ \ WebDriverManager.chromedriver().setup();/\ \ \ \ System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

RUN sed -i -e 's/\ \ \ \ val\ chromeDriver\ =\ ChromeDriver(chromeOptions)/\ \ \ \ System.setProperty("webdriver.chrome.whitelistedIps", "");\n\ \ \ \ chromeOptions.addArguments\("--no-sandbox"\);\n\ \ \ \ chromeOptions.addArguments\("--disable-dev-shm-usage"\);\n\ \ \ \ val\ chromeDriver\ =\ ChromeDriver\(chromeOptions\)/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# run gradle build
RUN cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt && \
    /opt/gradle/gradle-7.0/bin/gradle build && \
    cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# setup vnc
RUN echo "# XScreenSaver Preferences File\nmode:		off\nselected:  -1" > /root/.xscreensaver && \
  cat /root/.xscreensaver && mkdir /root/.vnc/ && \
  echo "#!/bin/sh\n/usr/bin/autocutsel -s CLIPBOARD -fork\nxrdb $HOME/.Xresources\nxsetroot -solid grey\n#x-terminal-emulator -geometry  80x24+10+10 -ls -title \"$VNCDESKTOP Desktop\" &\n#x-window-manager &\n# Fix   to make GNOME work\nexport XKL_XMODMAP_DISABLE=1\n/etc/X11/Xsession  &\nx-terminal-emulator -e \"/opt/gradle/gradle-7.0/bin/gradle run 2>&1 | tee  /app/impflog\"" > /root/.vnc/xstartup && \
  chmod +x /root/.vnc/xstartup && \
  cat /root/.vnc/xstartup && \
  mv /usr/share/novnc/vnc.html /usr/share/novnc/index.html && \
  echo "#!/bin/bash\necho -n \${VNC_PASSWORD:-impf-bot} | vncpasswd -f > /root/.vnc/passwd\nchmod 400 ~/.vnc/passwd\n\nexport USER=root\nvncserver :1 -geometry 1920x1080 -depth 24 && websockify -D --web=/usr/share/novnc/ 6901 localhost:5901\ntail -f /app/impflog" > /root/vnc-startup.sh && \
  chmod +x /root/vnc-startup.sh && \
  cat /root/vnc-startup.sh && \
  chmod go-rwx /root/.vnc 

RUN wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

RUN dpkg -i chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

EXPOSE 5901
EXPOSE 6901

CMD ["/root/vnc-startup.sh"]
```

Yes, thats a good idea, would be nice if you want to write the Documentation for it.

Here is a updated Dockerfile, I also made a pull request for it.
https://github.com/TobseF/impf-bot/pull/55

To build the container with a Dockerfile with a different name, use 
`
docker build . -f Dockerfile_ARM impf-bot
`

The new Dockerfile automatically patches 
`
To get it to work, replace
WebDriverManager.chromedriver().setup(); in src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt
with System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)
`

, so if I didnt forget anything, no external patches should be needed aside from building the container

Would be nice if you could test the new Dockerfile with a fresh clone of the repository just to see if it works ^^

**Comment by atpanos** [comment]
For me on raspberry pi 4 does not work.
Can you maybe push an image to dockerhub for arm?

**Comment by Pfuenzle** [comment]
I'll have to look into how I can do that, as I don't have a ARM device at home. What error do you get when building it yourself?

**Comment by atpanos** [comment]
First the chrome version can't be found. I updated it to the ..212-1.

And then at the end the Gradle build failed.
But it did not say any specific. Only use --stacktrace to get more output.

But ok, I thought you are also working on arm, I can maybe look into it myself also.

```
Step 9/15 : RUN cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt &&     /opt/gradle/gradle-7.0/bin/gradle build &&     cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt
 ---> Running in fb5b66b3fb07
package de.tfr.impf.selenium

import de.tfr.impf.config.Config
import io.github.bonigarcia.wdm.WebDriverManager
import org.openqa.selenium.WebDriver
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions
import java.util.concurrent.TimeUnit

fun createDriver(): ChromeDriver {
    System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)
    val chromeOptions = ChromeOptions()
    if (Config.hasUserAgent) {
        chromeOptions.addArguments("general.useragent.override", Config.userAgent)
    }
    System.setProperty("webdriver.chrome.whitelistedIps", "");
    chromeOptions.addArguments("--no-sandbox");
    chromeOptions.addArguments("--disable-dev-shm-usage");
    val chromeDriver = ChromeDriver(chromeOptions)
    chromeDriver.setTimeOut(Config.searchElementTimeout())
    return chromeDriver
}

fun WebDriver.setTimeOut(milliseconds: Long) {
    this.manage()?.timeouts()?.implicitlyWait(milliseconds, TimeUnit.MILLISECONDS)
}

Welcome to Gradle 7.0!

Here are the highlights of this release:
 - File system watching enabled by default
 - Support for running with and building Java 16 projects
 - Native support for Apple Silicon processors
 - Dependency catalog feature preview

For more details see https://docs.gradle.org/7.0/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileKotlin
e: /app/src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt: (11, 31): Unresolved reference: nameDriver
e: /app/src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt: (11, 50): Unresolved reference: pathDriver
e: /app/src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt: (11, 70): Unresolved reference: exeDriver

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 17s
1 actionable task: 1 executed
The command '/bin/sh -c cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt &&     /opt/gradle/gradle-7.0/bin/gradle build &&     cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt' returned a non-zero code: 1
```

If I see it correct the dockerfile replaces the chrome driver path with the ones in the config. But in the config they got removed some time ago.

**Comment by Bergdoc** [comment]
@atpanos 
You have to add to config.properties:

`
pathDriver = /usr/bin/
nameDriver = webdriver.chrome.driver
exeDriver = chromedriver
`

Or adjust directly the line in the docker file:

`
RUN sed -i -e 's/\ \ \ \ WebDriverManager.chromedriver().setup();/\ \ \ \ System.setProperty(Config.nameDriver, Config.pathDriver + Config.exeDriver)/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt
`

**Comment by Pfuenzle** [comment]
Oh good find, nameDriver, pathDriver and exeDriver is not in the config anymore.

Could you please try out following Dockerfile? Thanks

```
FROM debian:buster

# install apt dependencies
RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y unzip wget git default-jdk chromium=90.0.4430.93-1~deb10u1 xorg tightvncserver autocutsel lxde-core novnc python-websockify 

WORKDIR /app

# download gradle
RUN wget https://services.gradle.org/distributions/gradle-7.0-bin.zip  -P /tmp/ && \
    unzip -d /opt/gradle /tmp/gradle-7.0-bin.zip && \
    rm -rf /tmp/gradle-7.0-bin.zip

# copy whole folder into container
COPY . .

RUN sed -i -e 's/\ \ \ \ WebDriverManager.chromedriver().setup();/\ \ \ \ System.setProperty(\"webdriver.chrome.driver\", \"/app/chromedriver\")/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

RUN sed -i -e 's/\ \ \ \ val\ chromeDriver\ =\ ChromeDriver(chromeOptions)/\ \ \ \ System.setProperty("webdriver.chrome.whitelistedIps", "");\n\ \ \ \ chromeOptions.addArguments\("--no-sandbox"\);\n\ \ \ \ chromeOptions.addArguments\("--disable-dev-shm-usage"\);\n\ \ \ \ val\ chromeDriver\ =\ ChromeDriver\(chromeOptions\)/g' src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# run gradle build
RUN cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt && \
    /opt/gradle/gradle-7.0/bin/gradle build && \
    cat src/main/kotlin/de/tfr/impf/selenium/DriverFactory.kt

# setup vnc
RUN echo "# XScreenSaver Preferences File\nmode:		off\nselected:  -1" > /root/.xscreensaver && \
  cat /root/.xscreensaver && mkdir /root/.vnc/ && \
  echo "#!/bin/sh\n/usr/bin/autocutsel -s CLIPBOARD -fork\nxrdb $HOME/.Xresources\nxsetroot -solid grey\n#x-terminal-emulator -geometry  80x24+10+10 -ls -title \"$VNCDESKTOP Desktop\" &\n#x-window-manager &\n# Fix   to make GNOME work\nexport XKL_XMODMAP_DISABLE=1\n/etc/X11/Xsession  &\nx-terminal-emulator -e \"/opt/gradle/gradle-7.0/bin/gradle run 2>&1 | tee  /app/impflog\"" > /root/.vnc/xstartup && \
  chmod +x /root/.vnc/xstartup && \
  cat /root/.vnc/xstartup && \
  mv /usr/share/novnc/vnc.html /usr/share/novnc/index.html && \
  echo "#!/bin/bash\necho -n \${VNC_PASSWORD:-impf-bot} | vncpasswd -f > /root/.vnc/passwd\nchmod 400 ~/.vnc/passwd\n\nexport USER=root\nvncserver :1 -geometry 1920x1080 -depth 24 && websockify -D --web=/usr/share/novnc/ 6901 localhost:5901\ntail -f /app/impflog" > /root/vnc-startup.sh && \
  chmod +x /root/vnc-startup.sh && \
  cat /root/vnc-startup.sh && \
  chmod go-rwx /root/.vnc 

RUN wget http://security.debian.org/debian-security/pool/updates/main/c/chromium/chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

RUN dpkg -i chromium-driver_90.0.4430.93-1~deb10u1_armhf.deb

RUN copy /usr/bin/chromedriver /app/chromedriver

EXPOSE 5901
EXPOSE 6901

CMD ["/root/vnc-startup.sh"]

```

Edit: Whoops Bergdoc was a minute faster :P
But as he said, I replaced the paths with the right ones

**Comment by atpanos** [comment]
I managed to get it to work.
Will commit my changes tomorrow.
But I still get only 429...

Somehow the rpi4 runs always into the bot protection. Maybe user-agent check for arm?

**Comment by Bergdoc** [comment]
I did not run into 429, are you using default timings?

**Comment by atpanos** [comment]
Tried default yes.
Also increased them, no change.

**Comment by Bergdoc** [comment]
strange, on which server (e.g. 001) are you getting the errors? I'll try to reproduce it tomorrow

**Comment by Pfuenzle** [comment]
Thats very likely no ARM-specifc issue, also you can try to change the useragent with the config file

**Comment by atpanos** [comment]
> strange, on which server (e.g. 001) are you getting the errors? I'll try to reproduce it tomorrow

On all, 001, 002, 003, 005, 229
