### ISSUE TITLE
Question: Age Feld

### ISSUE THREAD

**Issue by Apfelwurm** [TobseF/impf-bot#64]
Hi zusammen,
ich habe mir eben das Projekt angeschaut und wollt mich zunächst bei allen contributenden für die tolle Arbeit bedanken :)

Ich habe eine kurze Frage, bei der ich aber nicht weiß ob sie hier überhaupt von jemandem beantwortet werden kann:
In wie weit entscheidet das Age Feld über die Ausgabe von freien Terminen? Im konkreten Fall liegt eine Impfbescheinigung vor, weshalb das Alter zunächst für die Entscheidung der Impfberechtigung keine Rolle spielen dürfte. Oder geht es hier darum welcher Impfstoff zur Verfügung steht?

Falls das jemand weiß wäre ich dankbar! :)

**Comment by Pfuenzle** [comment]
Weiß jetzt nichts internes, aber bei mir hab ich z.B. für meinen Opa was gesucht und sein Alter eingegeben, und da er über 60 ist und Astra Zeneca bekommen darf, gab es für ihn einen Termin, als ich dann aber mein Alter eingegeben habe, gab es keinen mehr, da Astra für meine Altersgruppe nicht empfohlen ist.

Also falls Astra Zeneca verfügbar: Nur Termin falls Alter über 60
Falls anderer Impfstoff: Alter egal (zumindest meiner Erfahrung nach, falls Falsch bitte korrigieren)

Also hast Recht, es geht um den verteilten Impfstoff

**Comment by Apfelwurm** [comment]
Dankeschön für die Erklärung :)

**Comment by Bergdoc** [comment]
Das Alter ist relevant für die Bestimmung der Leistungsmerkmale (welcher Impfstoff)

L920 = Biontech für 16-17jährige
L921 = Biontech oder Moderna für 18+
L922 = AstraZeneca für 60+
L923 = Johnson & Johnson für 18+

siehe Issue: https://github.com/TobseF/impf-bot/issues/16
