### ISSUE TITLE
ist das ein Fehler oder weil keine Termine frei sind

### ISSUE THREAD

**Issue by EQ5** [TobseF/impf-bot#68]
Hallo,
erstmal danke für das zur Verfügung stellen des Bots,
ich habe eine Frage zu diesem Eintrag im Log ERROR ReportJob - Failed to check location: egal welche Location ich angebe.

Ist das ein Fehler oder weil gerade keine Termin zur Verfügung stehen?

Gruss Manuel

**Comment by Sebastian-G** [comment]
Hast du mal mittels VNC auf localhost:5901 deinem Browser zugeschaut (oder via Browser, siehe Doku)
Da das System ja nur dein Browser automatisiert, kannst du ja mal online die Liste durchschauen.

Es ist wichtig, dass der Name den du in der Config für eine Location angibst auch genau so in der Liste steht.

Ich habe es wie im Beispiel mit „PLZ OrtsName“ gemacht.

wenn du in Deinem lokalen Code das logging level auf debug erhöst, solltest etwas wie Folgendes sehen:

- Change State …
- Location: 70376 Stuttgart is full

**Comment by Fabbi** [comment]
Das Problem hatte ich auch. 

Das Problem bei mir war, dass ich ohne Vermittlungscode die Zentrums-ID angegeben habe. `parseLocation` erwartet aber `[`.
`72072 Tübingen(002)` geht also nicht, `72072 Tübingen[](002)` scheint aber zu funktionieren.

**Comment by Sebastian-G** [comment]
Die ServerID kann man auch weglassen, da der Bot ohnehin nur die UI verwendet und keine API Shortcuts verwendet.

Daher geht auch z.B. `"72072 Tübingen,7..."`

**Comment by EQ5** [comment]
Formatierung der config.porperties hat den Fehler behoben. Musste das File expliziert als UTF-8 formatieren.
