### ISSUE TITLE
[Bug]Impfservice site goes to main page and bots thinks there are free vaccination dates

### ISSUE THREAD

**Issue by SAMUD** [TobseF/impf-bot#7]
Hi,

I'am running this software since this morning. From time to time I get this:

```
03.05 11:59:09 INFO ReportJob - Found free vaccination dates in location  **********:https://002-iz.impfterminservice.de/impftermine
Ten minutes left to choose a date.
```

But when I go to the chrome Windows I see this:
![image](https://user-images.githubusercontent.com/10502656/116864203-c680a400-ac07-11eb-8758-88abd6a41d50.png)

Whats going on here?

**Comment by lk3de** [comment]
Sometimes, after you enter the Vermittlungscode and click on "Termin buchen", the system just forwards you back to the home page - for whatever reason, I also couldn't figure it out yet. It even happens sometimes if you click the official "Termine buchen" link from the email that contains your Vermittlungscode.

Can probably fixed inside of `searchForVaccinateDate()`, by checking if the button that we want to click exists at all, and throw an exception if not.

**Comment by SAMUD** [comment]
Hmm......
The code is running since around 9 oclock this morning and I had about 5 of those events happen so far. 

I know nothing about Kotlin, so I am going to leave this for someone more experienced to fix :)

**Comment by madrhr** [comment]
check on devtools if you got HTTP 429 back, sometimes you get blocked radomly

**Comment by TobseF** [comment]
Um möglichen Limits entgegen zu wirken, habe ich einige Timing Einstellungen in den Properties konfigurierbar gemacht. Außerdem wird nun auch der "Virtueller Warteraum" erkannt. Und dank dem Fix von @ncface auch noch das Fehlerfenster berücksichtigt.
