### ISSUE TITLE
ERROR ReportJob - Failed to check location:

### ISSUE THREAD

**Issue by Jupiops** [TobseF/impf-bot#75]
Im getting an error using the latest Docker Image

Stacktrace: [_impf-bot_impf-bot.1.s6kb6pwmjapj9a6b8galltolo_logs.txt](https://github.com/TobseF/impf-bot/files/6531844/_impf-bot_impf-bot.1.s6kb6pwmjapj9a6b8galltolo_logs.txt)

Im using this config:
```yaml
mainPageUrl = https://www.impfterminservice.de/impftermine
state = Baden-Württemberg
locations = 88212 Ravensburg[XXXX-XXXX-XXXX](229),88045 Friedrichshafen
```

**Comment by Jupiops** [comment]
Umlaut im state Attribut hat den Fehler verursacht, mit `state = Baden-W` gibt es jetzt keinen Fehler mehr, allerdings habe ich jetzt das Problem mit dem Vermittlungscode

**Comment by Bergdoc** [comment]
Was für ein Problem hast du mit dem Vermittlungscode?

**Comment by Jupiops** [comment]
Die letzten beiden Zeichen `6D` werden abgeschnitten

**Comment by Sebastian-G** [comment]
Dazu gibt es schon ein issue. Einfach selbst den master builden dann gehts.

Siehe #59
