### ISSUE TITLE
Donation Link fehlt

### ISSUE THREAD

**Issue by cYrAx157** [TobseF/impf-bot#80]
Hi,
Da der Bot mir und meinen Kollegen sehr dabei geholfen hat, Termine zu bekommen, ein fettes Danke von uns !
Hast du irgendwo einen Donation-Link oder sowas, das man dir nen virtuellen Kasten Bier schicken kann ? :-)

Also dann doch wieder zurück zu den Issues: "Der Donation Link fehlt" :-)

**Comment by TobseF** [comment]
Das freut mich sehr, dass der Bot so Vielen das Leben ein wenig erleichtern kann. Auch wenn es schon sehr traurig ist, das sowas überhaupt nötig ist und jedem, der sich händisch damit rumschlagen muss(te) kann einem leid tun.

Dieses Issue lasse ich ungern unbeantwortet. Grundsätzlich gebührt der Dank natürlich allen, die sich mittlerweile an den Projekt beteiligt haben... das sind mittlerweile allein 20 die mit Merge Requests Verbesserungen und neue Features mit eingebracht haben. Dazu kommen alle die Issues gestellt haben, die beantwortet oder sich sonst in Diskussionen beteiligt haben.

Ich hab zwar den initialen Aufbau gepushed und dokumentiert, aber ich kann da kaum stellvertretend für alle andern Gewinn daraus schlagen. Nur um dieses Issue zu schließen, habe ich dann trotzdem ne kleine Möglichkeit geschaffen mir eine Freude zu machen und mir [einen Donut zu kaufen](https://www.buymeacoffee.com/tobse) 🍩. In der README gibt es nun eine neue Section "Thank You" - ganz altruistisch versteht sich😉
