### ISSUE TITLE
[Frage] SMS Verifizierungs HTML Dokument öffnet sich

### ISSUE THREAD

**Issue by TornaxO7** [TobseF/impf-bot#81]
Zuersteinmal danke, dass Sie den Bot hier erstellt haben! 

Nachdem ich alles in die `impf-bot/src/main/resources/config.properties` Datei eingetragen und dann `gradle build` ausgeführt habe, öffnet sich bei mir auf einmal Chrome mit einer `impf-bot/build/resources/test/de/tfr/impf/page/SMS-Verifizierung.html` Datei. Ist das Absicht?

Ich verwende Arch Linux, falls diese Information hilft.

**Comment by Timwun** [comment]
Ja, es werden beim Builden die Tests ausgeführt. :)

Diese Tests beinhalten auch die SMS Verifizierung.

**Comment by TornaxO7** [comment]
Komisch, in den geöffneten HTML Dokumenten steht eine andere SMS. :thinking: Naja egal, danke für die Information!
