### ISSUE TITLE
Bot funktioniert auf dem Raspberry pi nicht

### ISSUE THREAD

**Issue by TornaxO7** [TobseF/impf-bot#84]
Hallo, ich würde gerne das Programm auf meinem Raspberry pi laufen lassen, jedoch bekomme ich folgende Fehlermeldung, wenn ich `gradle run` eingebe:

<details>

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'impf-bot'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

</details>

Auf meinem Haupt-PC funktioniert es aber.

# Reproduction steps (on the raspberry pi)
1. `git clone https://github.com/TobseF/impf-bot.git`
2. Die `src/main/resources/config.properties` Datei angepasst
3. `gradle build`

Output von `gradle build`:

<details>

```

> Task :buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies


BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
```

</details>

4. `gradle run`.
Output von `gradle run`:

<details>

```

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'impf-bot'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at
FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'impf-bot'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s https://help.gradle.org

BUILD FAILED in 3s
```

</details>

Wenn ich genau diese Schritte auf meinem PC mache, funktioniert es.

# Rest
Die Pakete habe ich folgendermaßen installiert (auf'm pi):
```bash
sudo apt install gradle chromium-chromedriver
```

**Comment by Timwun** [comment]
Hab es aufgegeben aufm Raspberry Pi zum laufen zu kriegen und einfach Docker auf meinen Pi installiert und das Dockerfile_ARM gebaut und ausgeführt. 

Chromedriver werden offiziell nicht für ARM gebaut. Zwar macht das z.B. Electron aber naja das Tool zum Downloaden lädt eben den falschen runter und auch ersetzen hat nicht sehr gut geklappt.

**Comment by ConradSchmidt** [comment]
Hi @TornaxO7,
ich hatte auch Probleme den ImpfBot auf einem Raspberry Pi (Model B+) zu starten, da der ImpfBot eine Version vom chromedriver installiert, die auf meinem Raspberry Pi nicht funktioniert.

1. [install java 14](https://learnraspberrypi.com/2020/11/25/run-java-14-on-raspberry-pi/)
2. `sudo apt install chromium-chromedriver chromium-browser` _(installs chromedriver)_
3. `git clone https://github.com/TobseF/impf-bot.git` _(clones repo)_
4. `cd impf-bot` _(changes directory)_
5. `chmod +x gradlew` _(marks gradlew as executable)_
6. `./gradlew -i build` _(start build with info logging)_
7. fails with:
```
/home/pi/.cache/selenium/chromedriver/linux32/91.0.4472.19/chromedriver
...
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:25041/status] to be available after 20020 ms
```
7.0. replace broken chromedriver (replace <cache_driver_dir> with the one from message):
7.1. `rm <cache_driver_dir>/chromedriver` _(removes broken driver)_
7.2. `cp /usr/bin/chromedriver <cache_driver_dir>/` _(copies working driver)_
8. `./gradlew run` _(start bot)_
9. fails with:
```
Exception in thread "main" org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
9.1 `pkill -f chromium`
9.2 `pkill -f jvm`
9.3 do 8 again
10. profit

**Comment by TornaxO7** [comment]
Hui, danke für die Anleitung! Es reicht aber glaub, wenn ich den Bot auf meinem Haupt-PC laufen lasse, während ich Arbeite (ist nicht böse gemeint). Ich bin mir aber sicher, dass es den Ein oder Anderen nützlich sein wird ^^
