### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by SanJSp** [TobseF/impf-bot#98]
As a developer, I'd like to re-use some of this code in my own personal projects and share those. For this, I would love to not interfere with any property rights and therefore I'd love to see an open-source license applied to this project.

Have you ever thought about it?

**Comment by TobseF** [comment]
Good point. I'm sure this code was already copied and used several times - without asking. In my opinion - sharing is caring and I want to make it as easy as possible to reuse any of my code. This is why I've chosen the https://unlicense.org.

📜 I just updated the info:
https://github.com/TobseF/impf-bot/commit/70917672af9b3ac05b5c3b0bee02bae482ecb6fd

Thanks for the hint!
